FROM ubuntu:16.04
MAINTAINER federico.sismondi@inria.fr

RUN apt-get update
RUN apt-get -y -qq install apt-utils
RUN apt-get -y -qq install python3-dev
RUN apt-get -y -qq install build-essential
RUN apt-get -y -qq install python3-setuptools
RUN	apt-get -y -qq install python3-pip
RUN	apt-get -y -qq install python-pip
RUN	apt-get -y -qq install supervisor
RUN apt-get -y -qq install net-tools
RUN apt-get -y install iputils-ping
RUN apt-get -y -qq install make

# upgrade pip
RUN python -m pip install --upgrade pip

# install aux ioppytest packages
RUN python -m pip install ioppytest-agent

# temp PATCH for avoiding https://github.com/celery/py-amqp/issues/191
RUN python -m pip install -Iv amqp==2.2.2

# launch processes
CMD ["/bin/echo", "No docker CMD nor ENTRYPOINT, see example in Dockerfile on how to run this"]

# example:
# > docker build -t tun_ecosystem_test_agent_from_debian -f tests/misc/dockerfile_for_ecosystem_test__agent_from_debian_base .
# > export AMQP_URL=amqp://paul:iamthewalrus@f-interop.rennes.inria.fr/jenkins.tun_ecosystem_test_agent_from_debian
# > docker run -it --sysctl net.ipv6.conf.all.disable_ipv6=0 --privileged tun_ecosystem_test_agent_from_debian ioppytest-agent  connect --name coap_client --url $AMQP_URL
