FROM python:3
MAINTAINER federico.sismondi@inria.fr

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update
RUN apt-get -y -qq install apt-utils
RUN apt-get -y -qq install python3-dev
RUN apt-get -y -qq install build-essential
RUN apt-get -y -qq install python3-setuptools
RUN	apt-get -y -qq install python3-pip
RUN	apt-get -y -qq install python-pip
RUN apt-get -y -qq install net-tools
RUN apt-get -y -qq install make

ADD . /ioppytest
ENV PATH="/ioppytest:$PATH"
WORKDIR /ioppytest

# Makefile entrypoint
RUN make install-python-dependencies

#RUN  groupadd -g 500 coap && useradd -u 500 -g 500 coap
#USER coap

# temp PATCH for avoiding https://github.com/celery/py-amqp/issues/191
RUN python3 -m pip install -Iv amqp==2.3.1
RUN python -m pip install -Iv amqp==2.3.1

# launch processes
CMD [ "python", "-m", "ioppytest.packet_router", "DUMMY_CFG_01"]
