FROM archlinux/base
MAINTAINER federico.sismondi@inria.fr

RUN pacman -Syu --noconfirm
# RUN apt-get -y -qq install apt-utils
RUN pacman -S --noconfirm python
RUN pacman -S --noconfirm python2
RUN pacman -S --noconfirm base-devel
RUN pacman -S --noconfirm python-setuptools
RUN pacman -S --noconfirm python2-setuptools
RUN	pacman -S --noconfirm python-pip
RUN	pacman -S --noconfirm python2-pip
RUN	pacman -S --noconfirm supervisor
RUN pacman -S --noconfirm net-tools
# RUN apt-get -y install iputils-ping
# RUN pacman -S --noconfirm make

# upgrade pip
RUN python -m pip install --upgrade pip

# install aux ioppytest packages
RUN python -m pip install ioppytest-agent

# temp PATCH for avoiding https://github.com/celery/py-amqp/issues/191
RUN python -m pip install -Iv amqp==2.2.2

# launch processes
CMD ["/bin/echo", "No docker CMD nor ENTRYPOINT, see example in Dockerfile on how to run this"]

# example:
# > docker build . -t tun_ecosystem_test_agent_from_archlix -f dockerfile_for_ecosystem_test__agent_from_archlinux_base
# > export AMQP_URL=amqp://paul:iamthewalrus@f-interop.rennes.inria.fr/jenkins.tun_ecosystem_test_agent_from_debian
# > docker run -it --sysctl net.ipv6.conf.all.disable_ipv6=0 --privileged tun_ecosystem_test_agent_from_debian ioppytest-agent  connect --name coap_client --url $AMQP_URL
