FROM debian:latest
MAINTAINER federico.sismondi@inria.fr

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update
RUN apt-get -y -qq install apt-utils
RUN apt-get -y -qq install python3-dev
RUN apt-get -y -qq install build-essential
RUN apt-get -y -qq install python3-setuptools
RUN	apt-get -y -qq install python3-pip
RUN	apt-get -y -qq install python-pip
RUN	apt-get -y -qq install supervisor
RUN apt-get -y -qq install net-tools
RUN apt-get -y install iputils-ping
RUN apt-get -y -qq install make

# upgrade pip
RUN python -m pip install --upgrade pip

# install aux ioppytest packages
RUN python -m pip install ioppytest-agent

# needed for python source code of automated-iut
COPY . /ioppytest
WORKDIR /ioppytest

# requirements on automated-iut python code
RUN python3 -m pip install -r automated_IUTs/requirements.txt

# temp PATCH for avoiding https://github.com/celery/py-amqp/issues/191
RUN python3 -m pip install -Iv amqp==2.2.2
RUN python -m pip install -Iv amqp==2.2.2

# copy source code's supervisor processes configuration file into docker image file system
COPY tests/misc/supervisor_file_for_ecosystem_test.ini /etc/supervisor/conf.d/supervisor_file_for_ecosystem_test.conf

# launch processes
ENTRYPOINT ["/usr/bin/supervisord", "--nodaemon"]


# # # EXAMPLES ON HOW TO USE THIS DOCKER CONTAINER WITH SUPERVISOR FOR SETTING UP THE TEST ENVIRONMENT # # #

# build docker image which launches agent + automated IUT
# > docker build . -t tun_ecosystem_test_agent_from_debian -f tests/misc/dockerfile_for_ecosystem_test__agent_from_debian_base
# > export AMQP_URL=amqp://paul:iamthewalrus@f-interop.rennes.inria.fr/jenkins.tun_ecosystem_test_agent_from_debian

# finally run docker container with correct options:
# > docker run -it --env AMQP_URL=$AMQP_URL --env NODE_NAME=node1 --env AGENT_NAME=agent1 --env AGENT_IPV6_PREFIX=bbbb --env AGENT_IPV6_HOST=1 --sysctl net.ipv6.conf.all.disable_ipv6=0 --privileged tun_ecosystem_test_agent_from_debian

# non condensed version:
# > docker run -it
#               --env AMQP_URL=$AMQP_URL
#               --env NODE_NAME=agent2
#               --env AGENT_NAME=agent1
#               --env AGENT_IPV6_PREFIX=bbbb
#               --env AGENT_IPV6_HOST=1
#               --sysctl net.ipv6.conf.all.disable_ipv6=0
#               --privileged
#               tun_ecosystem_test_agent_from_debian
#               supervisord -c tests/misc/supervisor_file_for_ecosystem_test.ini