FROM python:3
MAINTAINER federico.sismondi@inria.fr

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update
RUN apt-get -y -qq install apt-utils
RUN apt-get -y -qq install python3-dev
RUN apt-get -y -qq install build-essential
RUN apt-get -y -qq install python3-setuptools
RUN	apt-get -y -qq install python3-pip
RUN	apt-get -y -qq install python-pip
RUN apt-get -y -qq install net-tools
RUN apt-get -y -qq install make

ADD . /ioppytest
ENV PATH="/ioppytest:$PATH"
WORKDIR /ioppytest

# Makefile entrypoint
RUN make install-python-dependencies

#RUN  groupadd -g 500 coap && useradd -u 500 -g 500 coap
#USER coap

# temp PATCH for avoiding https://github.com/celery/py-amqp/issues/191
RUN python3 -m pip install -Iv amqp==2.2.2
RUN python -m pip install -Iv amqp==2.2.2

# launch processes
CMD [ "python", "-m", "ioppytest.packet_router", "COAP_CFG_01"]

# example:
# docker build . -t tun_ecosystem_test_packet_router -f tests/misc/dockerfile_for_ecosystem_test__packet_router
# export AMQP_URL=amqp://paul:iamthewalrus@f-interop.rennes.inria.fr/jenkins.tun_ecosystem_test_agent_from_debian
# docker run  --rm -it --env AMQP_EXCHANGE=$AMQP_EXCHANGE --env AMQP_URL=$AMQP_URL --privileged --sysctl net.ipv6.conf.all.disable_ipv6=0  tun_ecosystem_test_packet_router
