FROM debian:latest
MAINTAINER federico.sismondi@inria.fr

ENV DEBIAN_FRONTEND noninteractive

RUN apt-get update
RUN apt-get -y -qq install apt-utils
RUN apt-get -y -qq install python3-dev
RUN apt-get -y -qq install build-essential
RUN apt-get -y -qq install python3-setuptools
RUN	apt-get -y -qq install python3-pip
RUN	apt-get -y -qq install python-pip
RUN	apt-get -y -qq install supervisor
RUN apt-get -y -qq install net-tools
RUN apt-get -y install iputils-ping
RUN apt-get -y -qq install make

# upgrade pip
RUN python -m pip install --upgrade pip

# install aux ioppytest packages
RUN python -m pip install ioppytest-agent

# needed for python source code of automated-iut
COPY . /ioppytest
WORKDIR /ioppytest

# requirements on automated-iut python code
RUN python3 -m pip install -r automated_IUTs/requirements.txt

# temp PATCH for avoiding https://github.com/celery/py-amqp/issues/191
RUN python3 -m pip install -Iv amqp==2.2.2
RUN python -m pip install -Iv amqp==2.2.2

# copy source code's supervisor processes configuration file into docker image file system
COPY tests/misc/supervisor_file_for_ecosystem_test.ini /etc/supervisor/conf.d/supervisor_file_for_ecosystem_test.conf

# launch processes
ENTRYPOINT ["/usr/bin/supervisord", "--nodaemon"]