- name: Install supervisor
  apt: name=supervisor state=present

- name: Start supervisor service
  service: name=supervisor state=started enabled=true

- name: apt-get installs
  apt: pkg={{ item }} update_cache=yes cache_valid_time=3600
  become: True
  with_items:
    - default-jdk
    - default-jre
    - maven
    - git-core
    - python3
    - python3-dev
    - python3-pip
    - python3-setuptools
    - tcpdump
    - python
    - python-dev
    - python-pip
    - python-setuptools

- name: Install python requirements for coordinator
  tags: coap_test_suite
  become: True
  pip:
    requirements: "{{ testing_tool_dir }}/ioppytest/test_coordinator/requirements.txt"
    executable: pip3

- name: Install python requirements for sniffer
  tags: coap_test_suite
  become: True
  pip:
    requirements: "{{ testing_tool_dir }}/ioppytest/sniffer/requirements.txt"
    executable: pip3

- name: Install python requirements for TAT
  tags: coap_test_suite
  become: True
  pip:
    requirements: "{{ testing_tool_dir }}/ioppytest/test_analysis_tool/requirements.txt"
    executable: pip3

- name: Install python requirements for webserver (serving files)
  tags: coap_test_suite
  become: True
  pip:
    requirements: "{{ testing_tool_dir }}/ioppytest/webserver/requirements.txt"
    executable: pip3
    
- name: Install python requirements for utils
  tags: coap_test_suite
  become: True
  pip:
    requirements: "{{ testing_tool_dir }}/ioppytest/utils/requirements.txt"
    executable: pip3

- name: Install python3 requirements for agent
  tags: coap_test_suite
  become: True
  pip:
    requirements: "{{ testing_tool_dir }}/ioppytest/agent/requirements.txt"
    executable: pip3

- name: Install python (2.7) requirements for agent
  tags: coap_test_suite
  become: True
  pip:
    requirements: "{{ testing_tool_dir }}/ioppytest/agent/requirements.txt"
    executable: pip

- name: Build COAP plugtest server
  tags: coap_automated_iut
  become: True
  command: mvn package
  args:
    chdir: "{{ testing_tool_dir }}/automated_IUTs/coap_server_californium"
    creates: "{{ testing_tool_dir }}/automated_IUTs/coap_server_californium/target"

