---
- hosts: 127.0.0.1
  connection: local
  vars:
    unix_user: f-interop
    clone_dest: "/home/{{ unix_user }}/coap_testing_tool"

  tasks:

  - name: Install supervisor
    apt: name=supervisor state=present

  - name: Start supervisor service
    service: name=supervisor state=started enabled=true

  - name: apt-get installs
    apt: pkg={{ item }} update_cache=yes cache_valid_time=3600
    become: True
    with_items:
      - default-jdk
      - default-jre
      - maven
      - git-core
      - python3
      - python3-dev
      - python3-pip
      - python3-setuptools
      - tcpdump

  - name: Download last version of testing tool
    become: True
    git:
      clone: yes
      repo: https://gitlab.distantaccess.com/fsismondi/coap_testing_tool.git
      recursive: yes
      dest : "{{ clone_dest }}"

  - name: Install python requirements for coordinator
    tags: coap_test_suite
    become: True
    pip:
      requirements: "{{ clone_dest }}/coap_testing_tool/test_coordinator/requirements.txt"
      executable: pip3

  - name: Install python requirements for sniffer
    tags: coap_test_suite
    become: True
    pip:
      requirements: "{{ clone_dest }}/coap_testing_tool/sniffer/requirements.txt"
      executable: pip3

  - name: Install python requirements for TAT
    tags: coap_test_suite
    become: True
    pip:
      requirements: "{{ clone_dest }}/coap_testing_tool/test_analysis_tool/requirements.txt"
      executable: pip3

  - name: Install python requirements for webserver (serving files)
    tags: coap_test_suite
    become: True
    pip:
      requirements: "{{ clone_dest }}/coap_testing_tool/webserver/requirements.txt"
      executable: pip3

  - name: Copy plugtest server source files
    tags: automated_iut
    become: True
    copy:
      src: "{{ clone_dest }}/coap_testing_tool/automated_implementations/coap_server_californium"
      dest: "{{ clone_dest }}/coap_testing_tool/build-automated-iut"
      owner: "{{ unix_user }}"
      group: "{{ unix_user }}"

  - name: Build COAP plugtest server
    tags: coap_automated_iut
    become: True
    command: mvn package
    args:
      chdir: "{{ clone_dest }}/coap_testing_tool/build-automated-iut/coap_server_californium"
      creates: "{{ clone_dest }}/coap_testing_tool/build-automated-iut/coap_server_californium/target"

