---
- hosts: 127.0.0.1
  connection: local
  vars:
    clone_dest: /tmp/ansible_clone

  tasks:

  - name: Install supervisor
    apt: name=supervisor state=present

  - name: Start supervisor service
    service: name=supervisor state=started enabled=true

  - name: apt-get installs
    apt: pkg={{ item }} update_cache=yes cache_valid_time=3600
    tags: coap_test_suite
    become: True
    with_items:
      - default-jdk
      - default-jre
      - maven
      - git-core
      - python-dev
      - python-pip
      - python-setuptools
      - tcpdump

  - name: install pip
    action: easy_install name=pip

  - name: Download last version of testing tool
    become: True
    git:
      clone: yes
      repo: https://gitlab.distantaccess.com/fsismondi/coap_testing_tool.git
      recursive: yes
      dest : "{{ clone_dest }}/coap_testing_tool"
#        version={{ version }}

  - name: Install python requirements for coordinator
    become: True
    pip:
      requirements: "{{ clone_dest }}/coap_testing_tool/coap_testing_tool/test_coordinator/requirements.txt"

  - name: Install python requirements for sniffer
    become: True
    pip:
      requirements: "{{ clone_dest }}/coap_testing_tool/coap_testing_tool/sniffer/requirements.txt"

  - name: Install python requirements for TAT
    become: True
    pip:
      requirements: "{{ clone_dest }}/coap_testing_tool/coap_testing_tool/test_analysis_tool/requirements.txt"

  - name: Install python requirements for webserver (serving files)
    become: True
    pip:
      requirements: "{{ clone_dest }}/coap_testing_tool/coap_testing_tool/webserver/requirements.txt"

  - name: Copy plugtest server source files
    tags: coap
    become: True
    copy: src=../tat/coap_plugtest_server dest={{ finterop_proj_path }}/coap owner={{ unix_user }} group={{ unix_user }}

  - name: Build COAP plugtest server
    tags: coap
    become: True
    command: mvn package
    args:
      chdir: "{{ finterop_proj_path }}/coap/coap_plugtest_server"
      creates: "{{ finterop_proj_path }}/coap/coap_plugtest_server/target/"



#
#
#    - name: install dependencies
#      action: pip requirements={{project_root}}{{project_name}}/requirements.txt


#   version: 'rel1'

#  tasks:
#    - name: Install Java and maven
#      apt: pkg={{ item }} update_cache=yes cache_valid_time=3600
#      tags: coap
#      become: True
#      with_items:
#        - maven
#        - default-jdk
#        - tcpdump